### ISSUE TITLE
async callback example

### ISSUE THREAD

**Issue by staminna** [eljamaki01/NewsWatcher2RWeb#2]
Hi

I am trying the following example from the book

```
var async = require('async');
var fs = require('fs');

async.eachOfSeries(['package.json', 'server.js'], function(file, callback) {
  console.log('Reading file ' + file);
  fs.readFile(file, 'utf8', function read(err, data) {
    console.log(data);
    callback();
  });
  }, function (err) {
    if (err) {
      console.log('file failed loading');
    }
    else {
      console.log('All files successfully loaded');
    }
  }
);

```

> > server.js:8
>     callback();
>     ^
> 
> TypeError: callback is not a function
>     at read (/Users/jorgenunes/webdev/books/fullnode/server.js:8:5)
>     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

**Comment by eljamaki01** [comment]
I am not sure where those lines of code came from. I don't recognize them as being from the book of from the GitHub project. As far as a JavaScript error, this is because the function being used is missing the key parameter. You must include it, but don't need to use it. Thus, as you had it, the callback was not a function, but an integer.
https://caolan.github.io/async/v3/docs.html#eachOfSeries

Change
function(file, callback)
to be
function(file, key, callback)

**Comment by staminna** [comment]
That extra parameter worked, thanks!
It's from Part II, service layer, page 106 of your react version of the book. :)

**Comment by eljamaki01** [comment]
Ah! I had searched for eachOfSeries(). My example actually uses eachSeries() and does not have the key parameter!
